### ISSUE TITLE
exact match

### ISSUE THREAD

**Issue by richxrich** [Mazeakin/jquery-bootstrap-autofill#1]
Exact matches don't seem to work, I changed the following and it works fine for me, what do you think?

                        if (
                            v.toLowerCase() == text.toLowerCase() ||
                            v.toLowerCase().includes(text.toLowerCase())
                        )

**Comment by Gataquadrada** [comment]
Hello!
Can you provide me with an example of your exact match failing?

**Comment by Gataquadrada** [comment]
I can't quite remember why I decided to remove the exact match from the plugin. But, in the  most recent [update](https://github.com/Mazeakin/jquery-bootstrap-autofill/commit/e60cb1638bb7879fa6539c524ace2c8166be8fd2), I brought it back.
Thank you for your input.
